# Don't Change the version
version: 0.2.1

# Messages to Replace it with you Language
messages:
  no-permission: "&cYou don't have permission to do that!"
  no-console: "&cYou can't do that from the console!"
  set-prefix: "&aYou have set the Prefix"


